package action;

public class TestException {
    public static void main(String[] args) {
        try {
            int i = 1 / 1;
            System.out.println(i);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        System.out.println("fjdklsjflkdjflksadjl");
    }
}
